name: publish

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: ./.github/actions/setup
    - name: Build
      run: pnpm build

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run astro check

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run astro check
      - name: Test
        run: pnpm --recursive test:ci

  docker:
    runs-on: ubuntu-22.04
    needs: [build, test]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: harrybrwn
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Images
      run: docker buildx bake --file docker-bake.hcl --push
