name: release

'on':
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - name: Install deps
      run: yarn install
    - name: Build
      run: yarn build
    - name: Package
      run: |
        tar \
          -czf harrybrwn.github.io.tar.gz \
          --transform 's/dist/h3y.sh/' \
          ./dist/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          harrybrwn.github.io.tar.gz
