name: release

'on':
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: ./.github/actions/setup
    - name: Build
      run: pnpm build
    - name: Package
      run: |
        tar \
          -czf harrybrwn.github.io.tar.gz \
          --transform 's/dist/h3y.sh/' \
          ./dist/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          harrybrwn.github.io.tar.gz
