name: test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: ./.github/actions/setup
    - name: Build
      run: pnpm build

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run astro check

  test:
    runs-on: ubuntu-22.04
    needs: [build, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run astro check
      - name: Test
        run: pnpm --recursive test:ci

