name: test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - name: Install deps
      run: yarn install
    - name: Build
      run: yarn build
    - name: Check
      run: yarn astro check
